"""restore deleted tables

Revision ID: 9b3f4e3b25c3
Revises: fa59abe1209a
Create Date: 2025-11-20 15:37:04.552266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3f4e3b25c3'
down_revision = 'fa59abe1209a'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
