"""add tiktok tables

Revision ID: fa59abe1209a
Revises: 7b0de8f3f8c4
Create Date: 2025-11-20 15:27:29.532764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa59abe1209a'
down_revision = '7b0de8f3f8c4'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_adset_or_adgroup',
    sa.Column('adset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('external_adset_id', sa.Text(), nullable=True),
    sa.Column('adset_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['dim_campaign.campaign_id'], ),
    sa.PrimaryKeyConstraint('adset_id')
    )
    op.create_table('dim_ad',
    sa.Column('ad_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adset_id', sa.Integer(), nullable=False),
    sa.Column('external_ad_id', sa.Text(), nullable=True),
    sa.Column('ad_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['adset_id'], ['dim_adset_or_adgroup.adset_id'], ),
    sa.PrimaryKeyConstraint('ad_id')
    )
    op.create_foreign_key(None, 'fact_marketing_daily', 'dim_adset_or_adgroup', ['adset_id'], ['adset_id'])
    op.create_foreign_key(None, 'fact_marketing_daily', 'dim_ad', ['ad_id'], ['ad_id'])
    op.alter_column('stg_shopify_daily_city', '_ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stg_shopify_daily_city', '_ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'fact_marketing_daily', type_='foreignkey')
    op.drop_constraint(None, 'fact_marketing_daily', type_='foreignkey')
    op.drop_table('dim_ad')
    op.drop_table('dim_adset_or_adgroup')
    # ### end Alembic commands ###
